name: BuilderCoffeeCommons
version: 0.1
description: Commons for Builders Coffe.
author: Ketsu_sama
main: eu.builderscoffee.commons.bukkit.Main
depend: [ BuildersCoffeeAPI, LuckPerms ]
commands:
  network:
    description: Ouvre le menu network
  menu:
    description: Ouvre le menu network
  profil:
    description: Ouvre le menu profil
  hub:
    description: Se déplace dans le serveur hub
  lobby:
    description: Se déplace dans le serveur hub
  help:
    description: Help command
  staffchat:
    aliases: [ sc ]
    description: Staffchat command
  broadcast:
    aliases: [bc]
    description: Envoi un message important