name: BuilderCoffeeCommons
version: 0.1
description: Commons for Builders Coffe.
author: Ketsu_sama
main: eu.builderscoffee.commons.Main
depend: [ BuildersCoffeeAPI ]
commands:
  network:
    description: Ouvre le menu network